########################################################################################################################
# Environment Setup
########################################################################################################################
# Enable dotenv loading

set dotenv-load := true

# Define the file name to lookup for when loading environment variables

set dotenv-filename := ".just.env"
