########################################################################################################################
# Global just options
#
# https://just.systems/man/en/chapter_27.html
########################################################################################################################
# Allow duplicate variables to be able to overwrite them from imports

set allow-duplicate-variables := true

# Allow duplicate recipes to be able to overwrite them from imports

set allow-duplicate-recipes := true

########################################################################################################################
# Shell Setup
########################################################################################################################
# Define shell to be used to execute recipes

set shell := ["bash", "-ec"]
