package visualizer

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/vimaster/service-scorecard-generator/go/internal/scorecard"
)

const (
	questionMark       = "<sup>&nbsp;<b><i><u>?</u></i></b></sup>"
	autoGenerationInfo = "<!-- !!! THIS FILE IS AUTOGENERATED - DO NOT EDIT IT MANUALLY !!! -->"
	fileName           = "Service-Scorecard"
)

var autoGenerationHeader = autoGenerationInfo + "\n" + autoGenerationInfo + "\n" + autoGenerationInfo + "\n\n"
var historicCommentPattern = regexp.MustCompile(`<!--(.*?)-->`)

func ensureScorecardDirectory(outputPath string) error {
	return os.MkdirAll(filepath.Join(outputPath, fileName), 0o755)
}

func writeGeneratedOutput(outputPath string, relativePath string, content string, withHeader bool) error {
	fullPath := filepath.Join(outputPath, relativePath)
	if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
		return err
	}
	if withHeader {
		content = autoGenerationHeader + content
	}
	return os.WriteFile(fullPath, []byte(content), 0o644)
}

func generateCheckPages(outputPath string, runInfo scorecard.RunInfo) error {
	for _, groupName := range scorecard.GroupOrder {
		group := runInfo.GroupByName(groupName)
		for _, check := range group.Checks {
			if err := writeGeneratedOutput(outputPath, filepath.Join(fileName, check.Name+".md"), check.InfoPageContent, true); err != nil {
				return err
			}
		}
	}
	return nil
}

func getHistoricRunInfo(outputPath string, currentTime time.Time, targetFileName string) (*scorecard.HistoricRunInfo, error) {
	sevenDaysAgo := currentTime.Add(-7 * 24 * time.Hour)
	gitLog := exec.Command("git", "log", "-n", "1000", `--format=format:%h %ai`, "--date=iso")
	gitLog.Dir = outputPath
	commitsOutput, err := gitLog.Output()
	if err != nil || strings.TrimSpace(string(commitsOutput)) == "" {
		return nil, nil
	}
	type commitInfo struct {
		hash string
		when time.Time
	}
	commits := make([]commitInfo, 0)
	for _, line := range strings.Split(strings.ReplaceAll(string(commitsOutput), "\r\n", "\n"), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		parts := strings.Split(line, " ")
		if len(parts) < 4 {
			continue
		}
		commitTime, parseErr := time.Parse("2006-01-02 15:04:05 -0700", strings.Join(parts[1:], " "))
		if parseErr != nil {
			continue
		}
		commits = append(commits, commitInfo{hash: parts[0], when: commitTime})
	}
	if len(commits) == 0 {
		return nil, nil
	}
	sort.Slice(commits, func(i, j int) bool {
		left := commits[i].when.Sub(sevenDaysAgo)
		if left < 0 {
			left = -left
		}
		right := commits[j].when.Sub(sevenDaysAgo)
		if right < 0 {
			right = -right
		}
		return left < right
	})
	gitShow := exec.Command("git", "show", fmt.Sprintf("%s:./%s", commits[0].hash, filepath.Base(targetFileName)))
	gitShow.Dir = outputPath
	historicContent, err := gitShow.Output()
	if err != nil || strings.TrimSpace(string(historicContent)) == "" {
		return nil, nil
	}
	lines := strings.Split(strings.ReplaceAll(string(historicContent), "\r\n", "\n"), "\n")
	lastLine := ""
	for index := len(lines) - 1; index >= 0; index-- {
		if strings.TrimSpace(lines[index]) != "" {
			lastLine = lines[index]
			break
		}
	}
	match := historicCommentPattern.FindStringSubmatch(lastLine)
	if len(match) < 2 {
		return nil, nil
	}
	return scorecard.ParseHistoricRunInfo(match[1])
}

func removeFirstHeading(content string) string {
	lines := strings.Split(strings.ReplaceAll(content, "\r\n", "\n"), "\n")
	filtered := make([]string, 0, len(lines))
	for _, line := range lines {
		if strings.HasPrefix(line, "# ") {
			continue
		}
		filtered = append(filtered, line)
	}
	return strings.TrimSpace(strings.Join(filtered, "\n"))
}

func indentBlock(content string) string {
	lines := strings.Split(strings.ReplaceAll(content, "\r\n", "\n"), "\n")
	for index, line := range lines {
		lines[index] = "    " + line
	}
	return strings.Join(lines, "\n")
}

func getHistoricDeductions(runInfo *scorecard.HistoricRunInfo, fullPathToService string, checkName string) []scorecard.Deduction {
	if runInfo == nil {
		return nil
	}
	serviceScore, ok := runInfo.ServiceScores[fullPathToService]
	if !ok {
		return nil
	}
	return serviceScore.DeductionsByCheck[checkName]
}

func styleOfNumber(score *int) string {
	if score == nil {
		return "color:#6b7280"
	}
	switch {
	case *score >= 90:
		return "color:#15803d"
	case *score >= 80:
		return "color:#b45309"
	case *score >= 70:
		return "color:#c2410c"
	default:
		return "color:#b91c1c"
	}
}

func escapeTitle(title string) string {
	return strings.NewReplacer("&", "&amp;", `"`, "&quot;", "<", "&lt;", ">", "&gt;").Replace(title)
}

type tableContent struct {
	Content string
	Title   string
	Colspan int
}

func formatMkDocsScore(checkValue []scorecard.Deduction, sevenDaysAgo []scorecard.Deduction) tableContent {
	finalScore := scorecard.CalculateFinalScore(checkValue)
	var finalScoreSevenDaysAgo *int
	if sevenDaysAgo != nil {
		finalScoreSevenDaysAgo = scorecard.CalculateFinalScore(sevenDaysAgo)
	}
	deltaString := formatDelta(finalScore, finalScoreSevenDaysAgo, `<sub><span title="compared to 7 days ago" style="color: #15803d"> ↑+%d%%</span></sub>`, `<sub><span title="compared to 7 days ago" style="color: #b91c1c"> ↓%d%%</span></sub>`)
	justifications := make([]string, 0, len(checkValue))
	for _, deduction := range checkValue {
		justifications = append(justifications, deduction.String())
	}
	display := "n/a"
	if finalScore != nil {
		display = fmt.Sprintf("%d", *finalScore)
	}
	return tableContent{Content: fmt.Sprintf(`<span style="%s">%s%s</span>`, styleOfNumber(finalScore), display, deltaString), Title: strings.Join(justifications, "&#10;"), Colspan: 1}
}

func formatPlainScore(checkValue []scorecard.Deduction, sevenDaysAgo []scorecard.Deduction, upTemplate string, downTemplate string, colorFunc func(*int) string) tableContent {
	finalScore := scorecard.CalculateFinalScore(checkValue)
	var finalScoreSevenDaysAgo *int
	if sevenDaysAgo != nil {
		finalScoreSevenDaysAgo = scorecard.CalculateFinalScore(sevenDaysAgo)
	}
	deltaString := formatDelta(finalScore, finalScoreSevenDaysAgo, upTemplate, downTemplate)
	justifications := make([]string, 0, len(checkValue))
	for _, deduction := range checkValue {
		justifications = append(justifications, deduction.String())
	}
	display := "n/a"
	if finalScore != nil {
		display = fmt.Sprintf("%d", *finalScore)
	}
	return tableContent{Content: fmt.Sprintf(`<span style="%s">%s%s</span>`, colorFunc(finalScore), display, deltaString), Title: strings.Join(justifications, "&#10;"), Colspan: 1}
}

func formatDelta(current *int, historic *int, upTemplate string, downTemplate string) string {
	if current == nil || historic == nil {
		return ""
	}
	delta := *current - *historic
	if delta == 0 {
		return ""
	}
	if delta > 0 {
		return fmt.Sprintf(upTemplate, delta)
	}
	return fmt.Sprintf(downTemplate, delta)
}

func toLatexScore(display string, score *int) string {
	color := "Gray"
	if score != nil {
		switch {
		case *score >= 90:
			color = "ForestGreen"
		case *score >= 80:
			color = "Goldenrod"
		case *score >= 70:
			color = "Orange"
		default:
			color = "Red"
		}
	}
	replacer := strings.NewReplacer(`\`, `\\`, `{`, `\{`, `}`, `\}`)
	return fmt.Sprintf(`$\textcolor{%s}{\mathsf{%s}}$`, color, replacer.Replace(display))
}

func mkDocsRemoveDates(content string, now time.Time) string {
	return scorecard.NormalizeDatePlaceholder(content, now.Format("2006-01-02"))
}
